flowchart LR
    %% 定义样式类
    classDef styleA fill:#F9E79F,stroke:#333,stroke-width:2px,rx:8px,ry:8px;
    classDef styleB fill:#A9DFBF,stroke:#333,stroke-width:2px,rx:8px,ry:8px;
    classDef styleC fill:#81D4FA,stroke:#333,stroke-width:2px,rx:8px,ry:8px;
    classDef styleD fill:#F8BBD0,stroke:#333,stroke-width:2px,rx:8px,ry:8px;
    
    %% 流程图节点
    A[设计一个模型] --> B[获取新数据]
    B --> C[更新模型]
    C --> D[检查是否够好]
    D --> B
    
    %% 绑定样式类
    class A styleA;
    class B styleB;
    class C styleC;
    class D styleD;